### ISSUE TITLE
Missing cs Files

### ISSUE THREAD

**Issue by alhalama** [lordmilko/SwitchvoxAPI#1]
When I try to compile this there are many missing .cs files from the repository:

1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Backups\GetList.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Backups\Remove.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Backups\Directories\GetInfo.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Backups\Directories\GetList.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\Sessions\GetList.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\ACLI\Sessions\GetInfo.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\ACLI\Sessions\GetList.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\ACLI\Sessions\GetLog.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Backups\Add.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\ACLI\StartSession.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Backups\Apply.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\ACLI\StopSession.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\Sessions\GetTypes.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PCAP\Sessions\GetInfo.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PCAP\Sessions\GetList.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PCAP\Sessions\GetLog.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PCAP\StartSession.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PCAP\StopSession.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PRI\Sessions\GetInfo.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PRI\Sessions\GetList.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PRI\Sessions\GetLog.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PRI\StartSession.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\git\SwitchvoxAPI\SwitchvoxAPI\SwitchvoxAPI\_Unimplemented\Debug\PRI\StopSession.cs' could not be found.

**Comment by lordmilko** [comment]
Hi @alhalama,

Thanks for raising this issue. I can see the .gitignore was ignoring these folders because they were called "Debug" and "Backup"

I have resolved this issue and confirmed the version of SwitchvoxAPI hosted on GitHub now compiles. Please let me know how you go.

Regards,
lordmilko

**Comment by alhalama** [comment]
I can confirm that I was able to build now after cloning the repository.
