### ISSUE TITLE
Link to "Latest Build" in Readme is dead, "Blob not found"

### ISSUE THREAD

**Issue by nittanygeek** [lordmilko/SwitchvoxAPI#10]
https://ci.appveyor.com/api/projects/lordmilko/switchvoxapi/artifacts/SwitchvoxAPI/bin/Release/SwitchvoxAPI.zip

Returns:
```
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:5a73de95-901e-00ed-29a6-8db360000000 Time:2019-10-28T15:43:01.2946533Z
</Message>
</Error>
```

**Comment by lordmilko** [comment]
Thanks @nittanygeek,

I have updated the README and have published the latest release to the [releases page](https://github.com/lordmilko/SwitchvoxAPI/releases)

Regards,
lordmilko
