### ISSUE TITLE
ContentType needs to change

### ISSUE THREAD

**Issue by cal5barton** [lordmilko/SwitchvoxAPI#3]
ContentType needs to be changed to application/xml to support the newer version Switchvox.

**Comment by lordmilko** [comment]
Hi @cal5fishbowl,

Thanks for raising this issue; I'll take a look into this

Are you able to advise which version of Switchvox you're using?

**Comment by cal5barton** [comment]
@lordmilko 
Looks like it's SMB Edition Version 6.5.2

**Comment by lordmilko** [comment]
Hi @cal5fishbowl,

I have confirmed that changing the content type to application/xml does not break compatibility with versions prior to 6.5.2, and as such have applied this fix.

Thanks for raising this issue!

Regards,
lordmilko
