### ISSUE TITLE
Switchvox updated to 6.7.1.2 and now server forcibly closes connection.

### ISSUE THREAD

**Issue by cal5barton** [lordmilko/SwitchvoxAPI#9]
Updated to the version below.
![image](https://user-images.githubusercontent.com/7515844/54942464-bfe5b580-4ef4-11e9-86ed-5efb748819bc.png)

Now every time I try to make a request the remote server closes the connection. Can you verify that this version is supported?

**Comment by lordmilko** [comment]
Hi @cal5barton,

Are you getting the exception `The underlying connection was closed: An unexpected error occurred on send`? If so, this indicates Switchvox 6.7.1.2 requires TLS 1.2, which older versions of the .NET Framework do not support by default.

Are you able to advise whether SwitchvoxAPI works if you do the following?

```c#
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
```

(requires `using System.Net`)

Regards,
lordmilko

**Comment by cal5barton** [comment]
@lordmilko Yes, that fixes my issue. Thanks!

**Comment by lordmilko** [comment]
Thanks @cal5barton,

I can see from the [release notes](https://support.digium.com/s/article/Updating-to-Switchvox-6-7-1?ui-force-components-controllers-recordGlobalValueProvider.RecordGvp.getRecord=1&r=6) that from Switchvox 6.7.1 TLS 1.0 and 1.1 have been disabled

The README has been updated with this information

Regards,
lordmilko
